inherit: 
    - models/pretrained.yaml
    - wandb.yaml

model:
    n_dims: 10
    n_positions: 101

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 15001
    curriculum:
        dims:
            start: 5
            end: 10
            inc: 1
            interval: 2000
