inherit: 
    - models/pretrained.yaml
    - wandb.yaml

model:
    n_dims: 2
    n_positions: 5

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 16
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 10000
    curriculum:
        dims:
            start: 1
            end: 2
            inc: 1
            interval: 2000
