
inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 4

training:
    task: seq_linear
    data: gaussian
    task_kwargs: {}
    batch_size: 1
    learning_rate: 0.0001
    save_every_steps: 500
    keep_every_steps: 500
    train_steps: 5001
    curriculum:
        dims:
            start: 2
            end: 2
            inc: 1
            interval: 2000
        points:
            start: 16
            end: 16
            inc: 2
            interval: 2000

out_dir: ../models/seq_linear

wandb:
    name: "seq_linear"
