inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 100
    n_positions: 100

training:
    task: seq_relu_2nn
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 50000
    curriculum:
        dims:
            start: 10
            end: 10
            inc: 1
            interval: 2000
        points:
            start: 100
            end: 100
            inc: 2
            interval: 2000

out_dir: ../models/seq_relu_2nn

wandb:
    name: "seq_relu_2nn"
