inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 20

training:
    task: seq_relu_2nn
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 50001
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 20
            end: 20
            inc: 2
            interval: 2000

out_dir: ../models/seq_relu_2nn

wandb:
    name: "seq_relu_2nn"
